# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d06ec81b1c3294e0785c8ad2a9efb57af2055d178d15530357a2285341a07a3243695f2944ddc7577988a550d7eb0ee3d162781f0d62b0309c10eb1df745c01

test:
  secret_key_base: 834c61bd0263444adb7f0ea277168563432f413a43bbeb9ed1d50fe6befce8c13d14859320e89be1b92c0c83df69ad1f7d82349ebd60b4966add95e8cfafdb95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
